export const mockGeneralPosts = [
    {
        id: 1,
        title: "Delar med mig av mina smultronställen",
        publishDate: "2026-07-18T13:44:00",
        likeCount: 2,
        name: "Xi Pi",
    },
    {
        id: 2,
        title: "Till dig som inte plockar upp efter hunden",
        publishDate: "2026-06-14T10:44:00",
        likeCount: 7,
        name: "Maria Persson",
    },
    {
        id: 3,
        title: "Möbler bortskänkes",
        publishDate: "2026-06-16T13:10:00",
        likeCount: 4,
        name: "Rosa Kvist",
    },
    {
        id: 4,
        title: "Uppstart av korpenlag i fotboll",
        publishDate: "2026-06-20T17:34:00",
        likeCount: 5,
        name: "Nils Möller",
    },
    {
        id: 5,
        title: "Tips på badställen",
        publishDate: "2026-06-23T12:21:00",
        likeCount: 2,
        name: "Gottfrid Nilsson",
    },
    {
        id: 6,
        title: "Hundpassning - behöver hjälp denna vecka",
        publishDate: "2026-06-23T16:10:00",
        likeCount: 1,
        name: "Maja Rosengren",
    },
    {
        id: 7,
        title: "Kompostering av trädgårdsavfall - tips?",
        publishDate: "2026-06-26T13:43:00",
        likeCount: 4,
        name: "Hans Jeppsson",
    },
    {
        id: 8,
        title: "Vad gör vi när det regnar hela sommaren?",
        publishDate: "2026-06-29T11:43:00",
        likeCount: 10,
        name: "Klara Boström",
    },
    {
        id: 9,
        title: "Nya grejor i lekeplatsen - mycket uppskattat!",
        publishDate: "2026-07-02T14:29:00",
        likeCount: 3,
        name: "Eva Vik",
    },
];