spring.datasource.url=jdbc:mysql://localhost:3306/bykanalen
spring.datasource.username=root
spring.datasource.password=3)Fch!0394!fVF

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=bykanalen
